<a href="https://colab.research.google.com/github/andrewi-bit/Data-Manipulation-with-Pandas/blob/main/Data_Types_and_Missing_Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
nolanbconaway_pitchfork_data_path = kagglehub.dataset_download('nolanbconaway/pitchfork-data')
datasnaek_chess_path = kagglehub.dataset_download('datasnaek/chess')
nasa_kepler_exoplanet_search_results_path = kagglehub.dataset_download('nasa/kepler-exoplanet-search-results')
residentmario_things_on_reddit_path = kagglehub.dataset_download('residentmario/things-on-reddit')
zynicide_wine_reviews_path = kagglehub.dataset_download('zynicide/wine-reviews')
residentmario_ramen_ratings_path = kagglehub.dataset_download('residentmario/ramen-ratings')
dansbecker_powerlifting_database_path = kagglehub.dataset_download('dansbecker/powerlifting-database')
datasnaek_youtube_new_path = kagglehub.dataset_download('datasnaek/youtube-new')
rtatman_188_million_us_wildfires_path = kagglehub.dataset_download('rtatman/188-million-us-wildfires')
jpmiller_publicassistance_path = kagglehub.dataset_download('jpmiller/publicassistance')

print('Data source import complete.')

Using Colab cache for faster access to the 'pitchfork-data' dataset.
Using Colab cache for faster access to the 'chess' dataset.
Using Colab cache for faster access to the 'kepler-exoplanet-search-results' dataset.
Using Colab cache for faster access to the 'things-on-reddit' dataset.
Using Colab cache for faster access to the 'wine-reviews' dataset.
Using Colab cache for faster access to the 'ramen-ratings' dataset.
Using Colab cache for faster access to the 'powerlifting-database' dataset.
Using Colab cache for faster access to the 'youtube-new' dataset.
Using Colab cache for faster access to the '188-million-us-wildfires' dataset.
Using Colab cache for faster access to the 'publicassistance' dataset.
Data source import complete.

**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/data-types-and-missing-values).**

---

# Introduction

Run the following cell to load your data and some utility functions.

In [6]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print("Setup complete.")

!wget -q -O winemag-data-130k-v2.csv https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv
reviews = pd.read_csv('winemag-data-130k-v2.csv', index_col=0)
reviews.head()
print("Setup complete.")

Setup complete.
Setup complete.

# Exercises

## 1.
What is the data type of the `points` column in the dataset?

In [7]:
# Your code here
dtype = reviews.points.dtype
dtype

dtype('int64')

## 2.
Create a Series from entries in the `points` column, but convert the entries to strings. Hint: strings are `str` in native Python.

In [8]:
point_strings =  reviews.points.astype(str)
point_strings

0         87
1         87
          ..
129969    90
129970    90
Name: points, Length: 129971, dtype: object

## 3.
Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [9]:
n_missing_prices =  reviews.price.isnull().sum()
n_missing_prices

np.int64(8996)

## 4.
What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the `region_1` field. This field is often missing data, so replace missing values with `Unknown`. Sort in descending order.  Your output should look something like this:

```
Unknown                    21247
Napa Valley                 4480
                           ...  
Bardolino Superiore            1
Primitivo del Tarantino        1
Name: region_1, Length: 1230, dtype: int64
```

In [10]:
reviews_per_region = reviews.region_1.fillna('Unknown').value_counts().sort_values(ascending=False)
reviews_per_region

region_1
Unknown                21247
Napa Valley             4480
                       ...
Bardolino Superiore        1
Paestum                    1
Name: count, Length: 1230, dtype: int64

# Keep going

Move on to **[renaming and combining](https://www.kaggle.com/residentmario/renaming-and-combining)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*