<a href="https://colab.research.google.com/github/andrewi-bit/Data-Manipulation-with-Pandas/blob/main/Renaming_and_Combining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
nolanbconaway_pitchfork_data_path = kagglehub.dataset_download('nolanbconaway/pitchfork-data')
datasnaek_chess_path = kagglehub.dataset_download('datasnaek/chess')
nasa_kepler_exoplanet_search_results_path = kagglehub.dataset_download('nasa/kepler-exoplanet-search-results')
residentmario_things_on_reddit_path = kagglehub.dataset_download('residentmario/things-on-reddit')
zynicide_wine_reviews_path = kagglehub.dataset_download('zynicide/wine-reviews')
residentmario_ramen_ratings_path = kagglehub.dataset_download('residentmario/ramen-ratings')
dansbecker_powerlifting_database_path = kagglehub.dataset_download('dansbecker/powerlifting-database')
datasnaek_youtube_new_path = kagglehub.dataset_download('datasnaek/youtube-new')
rtatman_188_million_us_wildfires_path = kagglehub.dataset_download('rtatman/188-million-us-wildfires')
jpmiller_publicassistance_path = kagglehub.dataset_download('jpmiller/publicassistance')

print('Data source import complete.')

Using Colab cache for faster access to the 'pitchfork-data' dataset.
Using Colab cache for faster access to the 'chess' dataset.
Using Colab cache for faster access to the 'kepler-exoplanet-search-results' dataset.
Using Colab cache for faster access to the 'things-on-reddit' dataset.
Using Colab cache for faster access to the 'wine-reviews' dataset.
Using Colab cache for faster access to the 'ramen-ratings' dataset.
Using Colab cache for faster access to the 'powerlifting-database' dataset.
Using Colab cache for faster access to the 'youtube-new' dataset.
Using Colab cache for faster access to the '188-million-us-wildfires' dataset.
Using Colab cache for faster access to the 'publicassistance' dataset.
Data source import complete.

**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/renaming-and-combining).**

---

# Introduction

Run the following cell to load your data and some utility functions.

In [7]:
from google.colab import files
uploaded = files.upload()

import zipfile, os

for fname in uploaded.keys():
    with zipfile.ZipFile(fname, 'r') as z:
        z.extractall(fname.replace('.zip', ''))
    print(fname, "berhasil di-extract")

!find . -name "*.csv"

Streaming output truncated to the last 5000 lines.
./archive/top-things/reddits/r/razer.csv
./archive/top-things/reddits/r/RBI.csv
./archive/top-things/reddits/r/RCSources.csv
./archive/top-things/reddits/r/ReallyBigShow.csv
./archive/top-things/reddits/r/randomgifts.csv
./archive/top-things/reddits/r/roguelikedev.csv
./archive/top-things/reddits/r/Rainbow6.csv
./archive/top-things/reddits/r/reactjs.csv
./archive/top-things/reddits/r/raisingkids.csv
./archive/top-things/reddits/r/roadtrip.csv
./archive/top-things/reddits/r/Robbaz.csv
./archive/top-things/reddits/r/researchchemicals.csv
./archive/top-things/reddits/r/RhodeIsland.csv
./archive/top-things/reddits/r/rwbyRP.csv
./archive/top-things/reddits/r/rocksmith.csv
./archive/top-things/reddits/r/reloading.csv
./archive/top-things/reddits/r/rugbyunion.csv
./archive/top-things/reddits/r/rockhounds.csv
./archive/top-things/reddits/r/raspberry_pi.csv
./archive/top-things/reddits/r/RealGirls.csv
./archive/top-things/reddits/r/redsox.csv
./archive/top-things/reddits/r/ReAlSaltLake.csv
./archive/top-things/reddits/r/riverdale.csv
./archive/top-things/reddits/r/residentevil.csv
./archive/top-things/reddits/r/RadicalChristianity.csv
./archive/top-things/reddits/r/realasians.csv
./archive/top-things/reddits/r/raisedbynarcissists.csv
./archive/top-things/reddits/r/RivalsOfAether.csv
./archive/top-things/reddits/r/Revolvers.csv
./archive/top-things/reddits/r/RationalPsychonaut.csv
./archive/top-things/reddits/r/Reprap.csv
./archive/top-things/reddits/r/RTLSDR.csv
./archive/top-things/reddits/r/RandomActsOfChristmas.csv
./archive/top-things/reddits/r/russia.csv
./archive/top-things/reddits/r/RedHotChiliPeppers.csv
./archive/top-things/reddits/r/RoastMe.csv
./archive/top-things/reddits/r/roguelikes.csv
./archive/top-things/reddits/r/regularcarreviews.csv
./archive/top-things/reddits/r/recruitinghell.csv
./archive/top-things/reddits/r/Roku.csv
./archive/top-things/reddits/r/runningmusic.csv
./archive/top-things/reddits/r/reallifedoodles.csv
./archive/top-things/reddits/r/RATS.csv
./archive/top-things/reddits/r/reflex.csv
./archive/top-things/reddits/r/radiocontrol.csv
./archive/top-things/reddits/r/ripcity.csv
./archive/top-things/reddits/r/rickygervais.csv
./archive/top-things/reddits/r/RoomPorn.csv
./archive/top-things/reddits/r/rollerblading.csv
./archive/top-things/reddits/r/RepLadies.csv
./archive/top-things/reddits/r/regularshow.csv
./archive/top-things/reddits/r/Rift.csv
./archive/top-things/reddits/r/Residency.csv
./archive/top-things/reddits/r/radiohead.csv
./archive/top-things/reddits/r/rawpetfood.csv
./archive/top-things/reddits/r/recipes.csv
./archive/top-things/reddits/r/RSDarkscape.csv
./archive/top-things/reddits/r/Roadcam.csv
./archive/top-things/reddits/r/RPI.csv
./archive/top-things/reddits/r/RBNLifeSkills.csv
./archive/top-things/reddits/r/reptiles.csv
./archive/top-things/reddits/r/RepublicofNE.csv
./archive/top-things/reddits/r/RWBY.csv
./archive/top-things/reddits/r/rosin.csv
./archive/top-things/reddits/r/RelayForReddit.csv
./archive/top-things/reddits/r/republicwireless.csv
./archive/top-things/reddits/r/RandomActsOfGaming.csv
./archive/top-things/reddits/r/racing.csv
./archive/top-things/reddits/r/ropetutorials.csv
./archive/top-things/reddits/r/Rowing.csv
./archive/top-things/reddits/r/RegularRevenge.csv
./archive/top-things/reddits/r/rfelectronics.csv
./archive/top-things/reddits/r/roasting.csv
./archive/top-things/reddits/r/rant.csv
./archive/top-things/reddits/r/Radiology.csv
./archive/top-things/reddits/r/rocketry.csv
./archive/top-things/reddits/r/rage.csv
./archive/top-things/reddits/r/ResearchVendors.csv
./archive/top-things/reddits/r/Rabbits.csv
./archive/top-things/reddits/r/rust.csv
./archive/top-things/reddits/r/RedditWritesSeinfeld.csv
./archive/top-things/reddits/r/rational.csv
./archive/top-things/reddits/r/rpg_gamers.csv
./archive/top-things/reddits/r/raisedbyborderlines.csv
./archive/top-things/reddits/r/RightwingLGBT.csv
./archive/top-things/reddits/r/racquetball.csv
./archive/top-things/reddits/r/RetroAR.csv
./archive/top-things/reddits/r/rockets.csv
./archive/top-things/reddits/r/Random_Acts_Of_Amazon.csv
./archive/top-things/reddits/r/rickandmorty.csv
./archive/top-things/reddits/r/reactivedogs.csv
./archive/top-things/reddits/r/riseagainst.csv
./archive/top-things/reddits/r/Reformed.csv
./archive/top-things/reddits/r/rccars.csv
./archive/top-things/reddits/r/ravens.csv
./archive/top-things/reddits/r/readyplayerone.csv
./archive/top-things/reddits/r/RedLetterMedia.csv
./archive/top-things/reddits/r/rum.csv
./archive/top-things/reddits/r/rubberducks.csv
./archive/top-things/reddits/r/reactiongifs.csv
./archive/top-things/reddits/r/russian.csv
./archive/top-things/reddits/r/RunningCirclejerk.csv
./archive/top-things/reddits/r/roblox.csv
./archive/top-things/reddits/r/relationships.csv
./archive/top-things/reddits/r/Redboid.csv
./archive/top-things/reddits/r/RocketLeague.csv
./archive/top-things/reddits/r/running.csv
./archive/top-things/reddits/r/RenewableEnergy.csv
./archive/top-things/reddits/r/RandomActsOfPolish.csv
./archive/top-things/reddits/r/RetroPie.csv
./archive/top-things/reddits/r/ronandfez.csv
./archive/top-things/reddits/r/RedvsBlue.csv
./archive/top-things/reddits/r/RagenChastain.csv
./archive/top-things/reddits/r/Rhetoric.csv
./archive/top-things/reddits/r/Runner5.csv
./archive/top-things/reddits/r/ram_trucks.csv
./archive/top-things/reddits/r/rollercoasters.csv
./archive/top-things/reddits/r/rit.csv
./archive/top-things/reddits/r/RBA.csv
./archive/top-things/reddits/r/rubyonrails.csv
./archive/top-things/reddits/r/Rockband.csv
./archive/top-things/reddits/r/RealEstate.csv
./archive/top-things/reddits/r/RandomActsOfVinyl.csv
./archive/top-things/reddits/r/raining.csv
./archive/top-things/reddits/r/raleigh.csv
./archive/top-things/reddits/z/Zippo.csv
./archive/top-things/reddits/z/Zappa.csv
./archive/top-things/reddits/z/zen.csv
./archive/top-things/reddits/z/zombies.csv
./archive/top-things/reddits/z/ZReviews.csv
./archive/top-things/reddits/z/zombicide.csv
./archive/top-things/reddits/z/Zoids.csv
./archive/top-things/reddits/z/ZBrush.csv
./archive/top-things/reddits/z/zootopia.csv
./archive/top-things/reddits/z/zoophilia.csv
./archive/top-things/reddits/z/zenfone3.csv
./archive/top-things/reddits/z/zerocarb.csv
./archive/top-things/reddits/z/zelda.csv
./archive/top-things/reddits/z/Zoomies.csv
./archive/top-things/reddits/z/ZeroWaste.csv
./archive/top-things/reddits/z/zenwatch.csv
./archive/top-things/reddits/v/VegRecipes.csv
./archive/top-things/reddits/v/VoiceActing.csv
./archive/top-things/reddits/v/Voltron.csv
./archive/top-things/reddits/v/VACsucks.csv
./archive/top-things/reddits/v/vegaslocals.csv
./archive/top-things/reddits/v/vegetarian.csv
./archive/top-things/reddits/v/videos.csv
./archive/top-things/reddits/v/veganketo.csv
./archive/top-things/reddits/v/ValhallaChallenge.csv
./archive/top-things/reddits/v/vizsla.csv
./archive/top-things/reddits/v/videography.csv
./archive/top-things/reddits/v/vainglorygame.csv
./archive/top-things/reddits/v/Vaping101.csv
./archive/top-things/reddits/v/Vermintide.csv
./archive/top-things/reddits/v/volcas.csv
./archive/top-things/reddits/v/VetTech.csv
./archive/top-things/reddits/v/vaginismus.csv
./archive/top-things/reddits/v/vintageaudio.csv
./archive/top-things/reddits/v/violinist.csv
./archive/top-things/reddits/v/volleyball.csv
./archive/top-things/reddits/v/vegetarianketo.csv
./archive/top-things/reddits/v/voroncorexy.csv
./archive/top-things/reddits/v/Veterans.csv
./archive/top-things/reddits/v/vegan.csv
./archive/top-things/reddits/v/VinylDeals.csv
./archive/top-things/reddits/v/vulkan.csv
./archive/top-things/reddits/v/vintageads.csv
./archive/top-things/reddits/v/vegan1200isplenty.csv
./archive/top-things/reddits/v/Vitamix.csv
./archive/top-things/reddits/v/VEDC.csv
./archive/top-things/reddits/v/vermont.csv
./archive/top-things/reddits/v/vexillology.csv
./archive/top-things/reddits/v/VHS.csv
./archive/top-things/reddits/v/VietNam.csv
./archive/top-things/reddits/v/VaporwaveAesthetics.csv
./archive/top-things/reddits/v/vita.csv
./archive/top-things/reddits/v/venturecapital.csv
./archive/top-things/reddits/v/vim.csv
./archive/top-things/reddits/v/valiant.csv
./archive/top-things/reddits/v/volt.csv
./archive/top-things/reddits/v/VideoEditing.csv
./archive/top-things/reddits/v/Vaporwave.csv
./archive/top-things/reddits/v/VOIP.csv
./archive/top-things/reddits/v/vancouver.csv
./archive/top-things/reddits/v/vzla.csv
./archive/top-things/reddits/v/veganfitness.csv
./archive/top-things/reddits/v/veganrecipes.csv
./archive/top-things/reddits/v/VeganFoodPorn.csv
./archive/top-things/reddits/v/VintageApple.csv
./archive/top-things/reddits/v/vintagecomputing.csv
./archive/top-things/reddits/v/virginislands.csv
./archive/top-things/reddits/v/vegancirclejerk.csv
./archive/top-things/reddits/v/venturebros.csv
./archive/top-things/reddits/v/VinylCollectors.csv
./archive/top-things/reddits/v/vfx.csv
./archive/top-things/reddits/v/Volkswagen.csv
./archive/top-things/reddits/v/Volvo.csv
./archive/top-things/reddits/v/VPN.csv
./archive/top-things/reddits/v/Velo.csv
./archive/top-things/reddits/v/verizon.csv
./archive/top-things/reddits/v/vexillologycirclejerk.csv
./archive/top-things/reddits/v/Vaping.csv
./archive/top-things/reddits/v/VinylReleases.csv
./archive/top-things/reddits/v/vandwellers.csv
./archive/top-things/reddits/v/VeryExpensive.csv
./archive/top-things/reddits/v/Vegetarianism.csv
./archive/top-things/reddits/v/vitahacks.csv
./archive/top-things/reddits/v/VIDEOENGINEERING.csv
./archive/top-things/reddits/v/vagabond.csv
./archive/top-things/reddits/v/VXJunkies.csv
./archive/top-things/reddits/v/vikingstv.csv
./archive/top-things/reddits/v/virtualreality.csv
./archive/top-things/reddits/v/vaporents.csv
./archive/top-things/reddits/v/venturacounty.csv
./archive/top-things/reddits/v/Vegan_Food.csv
./archive/top-things/reddits/v/VisitingIceland.csv
./archive/top-things/reddits/v/vcu.csv
./archive/top-things/reddits/v/VirginiaTech.csv
./archive/top-things/reddits/v/veg.csv
./archive/top-things/reddits/v/vegas.csv
./archive/top-things/reddits/v/Virginia.csv
./archive/top-things/reddits/v/valve.csv
./archive/top-things/reddits/v/Vive.csv
./archive/top-things/reddits/v/VeganBeauty.csv
./archive/top-things/reddits/v/vmware.csv
./archive/top-things/reddits/v/VeryCheap.csv
./archive/top-things/reddits/v/Vocaloid.csv
./archive/top-things/reddits/v/visualnovels.csv
./archive/top-things/reddits/v/vgb.csv
./archive/top-things/reddits/v/vinyl.csv
./archive/top-things/reddits/v/VictoriaBC.csv
./archive/top-things/reddits/g/Gunsforsale.csv
./archive/top-things/reddits/g/GhostRecon.csv
./archive/top-things/reddits/g/Galavant.csv
./archive/top-things/reddits/g/guitarpedals.csv
./archive/top-things/reddits/g/GGFreeForAll.csv
./archive/top-things/reddits/g/gundeals.csv
./archive/top-things/reddits/g/Grimdank.csv
./archive/top-things/reddits/g/gay_irl.csv
./archive/top-things/reddits/g/gamernews.csv
./archive/top-things/reddits/g/GenderCynical.csv
./archive/top-things/reddits/g/GamerGhazi.csv
./archive/top-things/reddits/g/girlsgonewired.csv
./archive/top-things/reddits/g/GirlswithGlasses.csv
./archive/top-things/reddits/g/gifs.csv
./archive/top-things/reddits/g/Glitch_in_the_Matrix.csv
./archive/top-things/reddits/g/gopro.csv
./archive/top-things/reddits/g/gamedev.csv
./archive/top-things/reddits/g/GrandTheftAutoV_PC.csv
./archive/top-things/reddits/g/GriefSupport.csv
./archive/top-things/reddits/g/gorillaz.csv
./archive/top-things/reddits/g/Gifts.csv
./archive/top-things/reddits/g/genesiscoupe.csv
./archive/top-things/reddits/g/gamingpc.csv
./archive/top-things/reddits/g/GreatXboxDeals.csv
./archive/top-things/reddits/g/google.csv
./archive/top-things/reddits/g/gis.csv
./archive/top-things/reddits/g/glutenfree.csv
./archive/top-things/reddits/g/getdisciplined.csv
./archive/top-things/reddits/g/germanshepherds.csv
./archive/top-things/reddits/g/GetMotivated.csv
./archive/top-things/reddits/g/gunpolitics.csv
./archive/top-things/reddits/g/gamecollecting.csv
./archive/top-things/reddits/g/GameSale.csv
./archive/top-things/reddits/g/gpdwin.csv
./archive/top-things/reddits/g/GunsAreCool.csv
./archive/top-things/reddits/g/gravityfalls.csv
./archive/top-things/reddits/g/GetEmployed.csv
./archive/top-things/reddits/g/GoRVing.csv
./archive/top-things/reddits/g/greatdanes.csv
./archive/top-things/reddits/g/Gamecube.csv
./archive/top-things/reddits/g/GalaxyS7.csv
./archive/top-things/reddits/g/GraphicsProgramming.csv
./archive/top-things/reddits/g/GrassHopperVape.csv
./archive/top-things/reddits/g/Gamingcirclejerk.csv
./archive/top-things/reddits/g/guineapigs.csv
./archive/top-things/reddits/g/grandorder.csv
./archive/top-things/reddits/g/GooglePixelC.csv
./archive/top-things/reddits/g/GoldandBlack.csv
./archive/top-things/reddits/g/gradadmissions.csv
./archive/top-things/reddits/g/GalaxyS8.csv
./archive/top-things/reddits/g/Genealogy.csv
./archive/top-things/reddits/g/GWNerdy.csv
./archive/top-things/reddits/g/GreenBayPackers.csv
./archive/top-things/reddits/g/GODZILLA.csv
./archive/top-things/reddits/g/gettingherselfoff.csv
./archive/top-things/reddits/g/gulag.csv
./archive/top-things/reddits/g/goodyearwelt.csv
./archive/top-things/reddits/g/geek.csv
./archive/top-things/reddits/g/GotG.csv
./archive/top-things/reddits/g/galaxys4.csv
./archive/top-things/reddits/g/generative.csv
./archive/top-things/reddits/g/golang.csv
./archive/top-things/reddits/g/GiftIdeas.csv
./archive/top-things/reddits/g/GearTrade.csv
./archive/top-things/reddits/g/GifRecipes.csv
./archive/top-things/reddits/g/gameofthrones.csv
./archive/top-things/reddits/g/GoodValue.csv
./archive/top-things/reddits/g/grilling.csv
./archive/top-things/reddits/g/goth.csv
./archive/top-things/reddits/g/Ghost_in_the_Shell.csv
./archive/top-things/reddits/g/GayChristians.csv
./archive/top-things/reddits/g/gzcl.csv
./archive/top-things/reddits/g/GreekMythology.csv
./archive/top-things/reddits/g/gallifrey.csv
./archive/top-things/reddits/g/GardenWild.csv
./archive/top-things/reddits/g/galaxynote5.csv
./archive/top-things/reddits/g/gayyoungold.csv
./archive/top-things/reddits/g/graphic_design.csv
./archive/top-things/reddits/g/godot.csv
./archive/top-things/reddits/g/Gotham.csv
./archive/top-things/reddits/g/gamegrumps.csv
./archive/top-things/reddits/g/GWABackstage.csv
./archive/top-things/reddits/g/graphicnovels.csv
./archive/top-things/reddits/g/Goruck.csv
./archive/top-things/reddits/g/GalaxyNote3.csv
./archive/top-things/reddits/g/GrandTheftAutoV.csv
./archive/top-things/reddits/g/GoogleCardboard.csv
./archive/top-things/reddits/g/GunsNRoses.csv
./archive/top-things/reddits/g/giantbomb.csv
./archive/top-things/reddits/g/Goldfish.csv
./archive/top-things/reddits/g/Gender_Critical.csv
./archive/top-things/reddits/g/GetSuave.csv
./archive/top-things/reddits/g/GameAudio.csv
./archive/top-things/reddits/g/GradeAUnderA.csv
./archive/top-things/reddits/g/gratefuldead.csv
./archive/top-things/reddits/g/gonewildaudio.csv
./archive/top-things/reddits/g/goldenretrievers.csv
./archive/top-things/reddits/g/GearsOfWar.csv
./archive/top-things/reddits/g/gso.csv
./archive/top-things/reddits/g/googleplaydeals.csv
./archive/top-things/reddits/g/Gore.csv
./archive/top-things/reddits/g/gwent.csv
./archive/top-things/reddits/g/GearVR.csv
./archive/top-things/reddits/g/glasgow.csv
./archive/top-things/reddits/g/GlobalOffensiveTrade.csv
./archive/top-things/reddits/g/gta5.csv
./archive/top-things/reddits/g/Glocks.csv
./archive/top-things/reddits/g/gatekeeping.csv
./archive/top-things/reddits/g/greenday.csv
./archive/top-things/reddits/g/golf.csv
./archive/top-things/reddits/g/GooglePixel.csv
./archive/top-things/reddits/g/GifSound.csv
./archive/top-things/reddits/g/GameDealsMeta.csv
./archive/top-things/reddits/g/getoffyourass.csv
./archive/top-things/reddits/g/guitars.csv
./archive/top-things/reddits/g/GearS3.csv
./archive/top-things/reddits/g/Gaming4Gamers.csv
./archive/top-things/reddits/g/GreenDawn.csv
./archive/top-things/reddits/g/geography.csv
./archive/top-things/reddits/g/guns.csv
./archive/top-things/reddits/g/galaxynote4.csv
./archive/top-things/reddits/g/GNV.csv
./archive/top-things/reddits/g/gaeilge.csv
./archive/top-things/reddits/g/gamingsuggestions.csv
./archive/top-things/reddits/g/Gamesnews.csv
./archive/top-things/reddits/g/getting_over_it.csv
./archive/top-things/reddits/g/GeeKnitting.csv
./archive/top-things/reddits/g/greentext.csv
./archive/top-things/reddits/g/GodofWar.csv
./archive/top-things/reddits/g/greatpyrenees.csv
./archive/top-things/reddits/g/gardening.csv
./archive/top-things/reddits/g/gif.csv
./archive/top-things/reddits/g/galaxys5.csv
./archive/top-things/reddits/g/gonewildcolor.csv
./archive/top-things/reddits/g/geophysics.csv
./archive/top-things/reddits/g/GaryJohnson.csv
./archive/top-things/reddits/g/ghibli.csv
./archive/top-things/reddits/g/Gunners.csv
./archive/top-things/reddits/g/gshock.csv
./archive/top-things/reddits/g/Guitar.csv
./archive/top-things/reddits/g/GeekyCrochet.csv
./archive/top-things/reddits/g/GameboyAdvance.csv
./archive/top-things/reddits/g/GradSchool.csv
./archive/top-things/reddits/g/greece.csv
./archive/top-things/reddits/g/gravesdisease.csv
./archive/top-things/reddits/g/GamePhysics.csv
./archive/top-things/reddits/g/GoneWildSmiles.csv
./archive/top-things/reddits/g/geocaching.csv
./archive/top-things/reddits/g/GGdiscussion.csv
./archive/top-things/reddits/g/gonewildstories.csv
./archive/top-things/reddits/g/grunge.csv
./archive/top-things/reddits/g/guitarpedalsjerk.csv
./archive/top-things/reddits/g/gadgets.csv
./archive/top-things/reddits/g/GirlGamers.csv
./archive/top-things/reddits/g/Gameboy.csv
./archive/top-things/reddits/g/geology.csv
./archive/top-things/reddits/g/gaybros.csv
./archive/top-things/reddits/g/gatech.csv
./archive/top-things/reddits/g/Gin.csv
./archive/top-things/reddits/g/grilledcheese.csv
./archive/top-things/reddits/g/googlehome.csv
./archive/top-things/reddits/g/Gunpla.csv
./archive/top-things/reddits/g/genderfluid.csv
./archive/top-things/reddits/g/genetics.csv
./archive/top-things/reddits/g/genderqueer.csv
./archive/top-things/reddits/g/GTAV.csv
./archive/top-things/reddits/g/GameDeals.csv
./archive/top-things/reddits/g/guitarporn.csv
./archive/top-things/reddits/g/GolfGTI.csv
./archive/top-things/reddits/g/guitarlessons.csv
./archive/top-things/reddits/g/GalaxyS6.csv
./archive/top-things/reddits/g/GiIvaSunner.csv
./archive/top-things/reddits/g/GayFreeUse.csv
./archive/top-things/reddits/g/GlitchInTheMatrix.csv
./archive/top-things/reddits/g/geopolitics.csv
./archive/top-things/reddits/g/GenderCritical.csv
./archive/top-things/reddits/g/GalaxyS3.csv
./archive/top-things/reddits/g/globalistshills.csv
./archive/top-things/reddits/g/GirlsFinishingTheJob.csv
./archive/top-things/reddits/g/Games.csv
./archive/top-things/reddits/g/glitch_art.csv
./archive/top-things/reddits/g/Greyhounds.csv
./archive/top-things/reddits/g/gaming.csv
./archive/top-things/reddits/g/GunFights.csv
./archive/top-things/reddits/g/gonewildcurvy.csv
./archive/top-things/reddits/g/GilmoreGirls.csv
./archive/top-things/reddits/g/gay.csv
./archive/top-things/reddits/g/Gundam.csv
./archive/top-things/reddits/g/GlobalOffensive.csv
./archive/top-things/reddits/g/GalaxyNote8.csv
./archive/top-things/reddits/g/GCdebatesQT.csv
./archive/top-things/reddits/g/GrandCherokee.csv
./archive/top-things/reddits/g/GalaxyNote7.csv
./archive/top-things/reddits/g/Graffiti.csv
./archive/top-things/reddits/g/Ghostbc.csv
./archive/top-things/reddits/g/grateful_dead.csv
./archive/top-things/reddits/g/German.csv
./archive/top-things/reddits/g/GakkouGurashi.csv
./archive/top-things/reddits/g/gametales.csv
./archive/top-things/reddits/g/GetStudying.csv
./archive/top-things/reddits/g/GayHiddenCams.csv
./archive/top-things/reddits/g/G502MasterRace.csv
./archive/top-things/reddits/g/gainit.csv

# Exercises

View the first several lines of your data by running the cell below:

In [10]:
!wget -q -O winemag-data-130k-v2.csv https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv
reviews = pd.read_csv('winemag-data-130k-v2.csv', index_col=0)

## 1.
`region_1` and `region_2` are pretty uninformative names for locale columns in the dataset. Create a copy of `reviews` with these columns renamed to `region` and `locale`, respectively.

In [11]:
# Your code here
renamed = reviews.rename(columns={'region_1': 'region', 'region_2': 'locale'})
renamed

,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## 2.
Set the index name in the dataset to `wines`.

In [12]:
reindexed = reviews.rename_axis('wines', axis='rows')
reindexed

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## 3.
The [Things on Reddit](https://www.kaggle.com/residentmario/things-on-reddit/data) dataset includes product links from a selection of top-ranked forums ("subreddits") on reddit.com. Run the cell below to load a dataframe of products mentioned on the */r/gaming* subreddit and another dataframe for products mentioned on the *r//movies* subreddit.

In [18]:
gaming_products = pd.read_csv("archive/top-things/reddits/g/gaming.csv")
gaming_products['subreddit'] = "r/gaming"

movie_products = pd.read_csv("archive/top-things/reddits/m/movies.csv")
movie_products['subreddit'] = "r/movies"

Create a `DataFrame` of products mentioned on *either* subreddit.

In [19]:
combined_products = pd.concat([gaming_products, movie_products])
combined_products

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
...,...,...,...,...,...,...
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies

## 4.
The [Powerlifting Database](https://www.kaggle.com/open-powerlifting/powerlifting-database) dataset on Kaggle includes one CSV table for powerlifting meets and a separate one for powerlifting competitors. Run the cell below to load these datasets into dataframes:

In [23]:
!find . -iname "meets.csv"
!find . -iname "openpowerlifting.csv"
!ls "archive (1)"
df_check = pd.read_csv("archive (1)/openpowerlifting.csv", nrows=5)
df_check.columns.tolist()

./archive (1)/openpowerlifting.csv
openpowerlifting-2024-01-06-4c732975.csv  openpowerlifting.csv

['Name',
 'Sex',
 'Event',
 'Equipment',
 'Age',
 'AgeClass',
 'Division',
 'BodyweightKg',
 'WeightClassKg',
 'Squat1Kg',
 'Squat2Kg',
 'Squat3Kg',
 'Squat4Kg',
 'Best3SquatKg',
 'Bench1Kg',
 'Bench2Kg',
 'Bench3Kg',
 'Bench4Kg',
 'Best3BenchKg',
 'Deadlift1Kg',
 'Deadlift2Kg',
 'Deadlift3Kg',
 'Deadlift4Kg',
 'Best3DeadliftKg',
 'TotalKg',
 'Place',
 'Wilks',
 'McCulloch',
 'Glossbrenner',
 'IPFPoints',
 'Tested',
 'Country',
 'Federation',
 'Date',
 'MeetCountry',
 'MeetState',
 'MeetName']

Both tables include references to a `MeetID`, a unique key for each meet (competition) included in the database. Using this, generate a dataset combining the two tables into one.

In [25]:
powerlifting_combined = pd.read_csv("archive (1)/openpowerlifting.csv")
powerlifting_combined

/tmp/ipykernel_590/2133653233.py:1: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  powerlifting_combined = pd.read_csv("archive (1)/openpowerlifting.csv")

,Name,Sex,Event,Equipment,Age,AgeClass,Division,BodyweightKg,WeightClassKg,Squat1Kg,...,McCulloch,Glossbrenner,IPFPoints,Tested,Country,Federation,Date,MeetCountry,MeetState,MeetName
0,Abbie Murphy,F,SBD,Wraps,29.0,24-34,F-OR,59.8,60,80.0,...,324.16,286.42,511.15,NaN,NaN,GPC-AUS,2018-10-27,Australia,VIC,Melbourne Cup
1,Abbie Tuong,F,SBD,Wraps,29.0,24-34,F-OR,58.5,60,100.0,...,378.07,334.16,595.65,NaN,NaN,GPC-AUS,2018-10-27,Australia,VIC,Melbourne Cup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423352,Stanisław Goroczko,M,SBD,Raw,63.5,60-64,Masters 2,80.8,83,-165.0,...,NaN,NaN,NaN,Yes,NaN,PZKFiTS,2017-04-01,Poland,NaN,Polish Classic Powerlifting Cup
1423353,Jan Sowa,M,SBD,Raw,70.5,70-74,Masters 2,82.0,83,-115.0,...,NaN,NaN,NaN,Yes,NaN,PZKFiTS,2017-04-01,Poland,NaN,Polish Classic Powerlifting Cup

# Congratulations!

You've finished the Pandas micro-course.  Many data scientists feel efficiency with Pandas is the most useful and practical skill they have, because it allows you to progress quickly in any project you have.

If you'd like to apply your new skills to examining geospatial data, you're encouraged to check out our **[Geospatial Analysis](https://www.kaggle.com/learn/geospatial-analysis)** micro-course.

You can also take advantage of your Pandas skills by entering a **[Kaggle Competition](https://www.kaggle.com/competitions)** or by answering a question you find interesting using **[Kaggle Datasets](https://www.kaggle.com/datasets)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*